### ISSUE TITLE
Add prettier to the project

### ISSUE THREAD

**Issue by Angelmmiguel** [Angelmmiguel/mmmusic.stream#7]
https://prettier.io/

**Comment by ganes1410** [comment]
can i do  this?

**Comment by Angelmmiguel** [comment]
Hello @ganes1410,

Sure, feel free to fork the repo and add prettier.

Thank you very much for contributing to the project! I hope you enjoy it :)

**Comment by ganes1410** [comment]
i added prettier .
what config should i use when running a script in package.json

**Comment by Angelmmiguel** [comment]
@ganes1410 you can use this config: https://prettier.io/docs/en/precommit.html#option-2-pretty-quick-https-githubcom-azz-pretty-quick.

**Comment by Angelmmiguel** [comment]
Closed by #8
